# Infer missing subDistrict

This notebook finds charges where `place_of_offence.address` is present but `place_of_offence.subDistrict` is missing.

For each such charge, it uses GPT-5.4 (Azure OpenAI) to infer the subDistrict from the address string, writes the inferred subDistrict back to `verified-features`, and exports an Excel file of cases where subDistrict could not be identified.

The default query filters out `exclude=True` records to match the active verified dataset used elsewhere in the repo.

In [3]:
import json
import os
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Optional
import re

import pandas as pd
from bson import ObjectId
from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field
from pymongo import MongoClient, UpdateOne

# Add parent to path so we can import featureExtraction modules
sys.path.insert(0, str(Path.cwd().parent))
from featureExtraction.utils.hkDistricts import SubDistrict, get_district_for_subdistrict

# Load env (try multiple locations like infer-missing-ages.ipynb)
for dotenv_path in (
    Path.cwd() / '.env',
    Path.cwd() / 'notebooks' / '.env',
    Path.cwd().parent / 'notebooks' / '.env',
    Path.cwd().parent / 'featureExtraction' / '.env',
):
    if dotenv_path.exists():
        load_dotenv(dotenv_path)
        break

# --- MongoDB connection ---
uri = os.getenv('DB_MONGODB_URI')
if not uri:
    raise RuntimeError('DB_MONGODB_URI is not set')

client = MongoClient(uri)
db = client.get_database(os.getenv('DB_NAME', 'drug-sentencing-predictor'))
verified_features = db.get_collection('verified-features')

# --- OpenAI client (Azure, gpt-5.4) ---
api_key = os.getenv('OPENAI_API_KEY')
base_url = os.getenv('OPENAI_BASE_URL')
if not api_key or not base_url:
    raise RuntimeError('OPENAI_API_KEY and OPENAI_BASE_URL must be set')

openai_client = OpenAI(api_key=api_key, base_url=base_url)
MODEL = os.getenv('MODEL', 'gpt-5.4')

pd.set_option('display.max_colwidth', None)

active_only = True

In [4]:
# Build the set of valid sub-district strings (from the enum)
VALID_SUBDISTRICTS = {sub.value for sub in SubDistrict}

print(f'Loaded {len(VALID_SUBDISTRICTS)} valid sub-districts from hkDistricts enum')
print(f'Sample: {sorted(VALID_SUBDISTRICTS)[:10]}...')

# Pydantic model for structured GPT response
class SubDistrictInference(BaseModel):
    subDistrict: Optional[str] = Field(
        description="The inferred sub-district name exactly as listed in the Hong Kong sub-district list. "
        "Set to null if the address does not clearly fall into one of the known sub-districts."
    )
    reason: str = Field(
        description="Brief reason for the inference (e.g., which landmarks/clues were used) "
        "or explanation for why it could not be determined."
    )

Loaded 127 valid sub-districts from hkDistricts enum
Sample: ['Aberdeen', 'Admiralty', 'Ap Lei Chau', 'Beacon Hill', 'Braemar Hill', 'Causeway Bay', 'Central', 'Chai Wan', 'Cheung Chau', 'Cheung Muk Tau']...

In [5]:
# Build the list of valid sub-district strings for the prompt
subdistrict_list_str = "\n".join(sorted(f"  - {s}" for s in VALID_SUBDISTRICTS))


def infer_subdistrict(address: str) -> SubDistrictInference:
    """Call GPT-5.4 to infer the HK sub-district from an address string.
    Returns a SubDistrictInference with the subDistrict value or None."""
    prompt = (
        "You are a Hong Kong geography specialist. Given an address in Hong Kong, determine "
        "which of the following sub-districts it belongs to.\n\n"
        "Valid sub-districts:\n"
        f"{subdistrict_list_str}\n\n"
        "Rules:\n"
        "1. Return the EXACT sub-district name as listed above (case-sensitive).\n"
        "2. If the address clearly matches a sub-district, return it.\n"
        "3. If the address is too vague, ambiguous, or does not match any known sub-district, "
        "set subDistrict to null and explain why.\n"
        "4. For well-known areas (e.g., 'Tsing Yi' → 'Tsing Yi', 'Mong Kok' → 'Mong Kok'), "
        "return the matching sub-district.\n"
        "5. For estate names, infer the approximate sub-district (e.g., 'Cheung Hong Estate' is in Tsing Yi).\n"
        "6. Do NOT guess if you are unsure — it is better to return null than a wrong sub-district."
    )

    response = openai_client.responses.parse(
        model=MODEL,
        input=[
            {"role": "system", "content": prompt},
            {"role": "user", "content": f"Address: {address}"},
        ],
        text_format=SubDistrictInference,
    )

    result: SubDistrictInference = response.output_parsed

    # Validate that the returned subDistrict is one of the valid enum values
    if result.subDistrict is not None and result.subDistrict not in VALID_SUBDISTRICTS:
        print(f"  WARNING: GPT returned invalid subDistrict '{result.subDistrict}' for address '{address}'")
        return SubDistrictInference(subDistrict=None, reason=f"Invalid sub-district returned: {result.subDistrict}")

    return result


# Test with a known address
test_result = infer_subdistrict("Room 1140, Hong Tai House, Cheung Hong Estate, Tsing Yi, New Territories")
print(f"Test address → subDistrict: {test_result.subDistrict}, reason: {test_result.reason}")

Test address → subDistrict: Tsing Yi, reason: Cheung Hong Estate is a public housing estate located on Tsing Yi Island, and the address explicitly includes 'Tsing Yi'.

In [7]:
# --- Query: find charges with address but no subDistrict ---

pipeline = []
if active_only:
    pipeline.append({'$match': {'exclude': {'$ne': True}}})

pipeline.extend([
    # Unwind charges to work at the charge level
    {'$unwind': '$judgement.charges'},
    # Filter to charges where place_of_offence exists and has a meaningful address
    {'$match': {
        'judgement.charges.place_of_offence': {'$ne': None},
        '$expr': {
            '$and': [
                # address must be non-null and non-empty
                {'$ne': ['$judgement.charges.place_of_offence.address', None]},
                {'$ne': ['$judgement.charges.place_of_offence.address', '']},
                # subDistrict must be null or empty string
                {'$or': [
                    {'$eq': ['$judgement.charges.place_of_offence.subDistrict', None]},
                    {'$eq': ['$judgement.charges.place_of_offence.subDistrict', '']},
                ]},
            ]
        },
    }},
    # Project the fields we need
    {
        '$project': {
            '_id': 1,
            'neutral_citation': '$judgement.neutral_citation',
            'charge_no': '$judgement.charges.charge_no',
            'address': '$judgement.charges.place_of_offence.address',
            'nature': '$judgement.charges.place_of_offence.nature',
            'subDistrict': '$judgement.charges.place_of_offence.subDistrict',
        }
    },
])

rows = list(verified_features.aggregate(pipeline, allowDiskUse=True))
print(f'Found {len(rows)} charges with address but missing subDistrict')

if rows:
    df = pd.DataFrame(rows)
    # Normalize ObjectId
    df['_id'] = df['_id'].apply(str)
    display(df.head(20))
else:
    print('No missing subDistrict cases found — all charges have subDistrict populated!')

Found 417 charges with address but missing subDistrict

,_id,neutral_citation,charge_no,address,nature,subDistrict
0,69c918e441df75d9210286be,[2021] HKDC 747,1,被告人所居住的單位,Residential building,None
1,69cf2b8dc96004cf50f0c5d3,[2025] HKCFI 1364,1,in the street near his home,Street,None
2,69cf2b8dc96004cf50f0c5d3,[2025] HKCFI 1364,2,inside the defendant's bedroom at his home,Residential building,None
3,69cf48d213addb9916257083,[2021] HKCFI 574,2,D1's residence,Residential building,None
4,69cf48de13addb9916257084,[2022] HKCFI 2407,2,Building - Unknown,Other,None
5,69cf4951a9f43af234c719ca,[2021] HKCFI 98,1,Post Office,Government or public building,None
6,69cf734bf9fafa2a2fe7d288,[2025] HKCFI 4134,1,Flat (6th floor of a building),Residential building,None
7,69cf734bf9fafa2a2fe7d288,[2025] HKCFI 4134,2,Flat (the said flat rented by the defendant),Residential building,None
8,69d0c87aa8276670f96f1761,[2023] HKDC 1856,1,Not Given,Other,None
9,69d373e2626c401b8b1c72da,[2023] HKCFI 925,1,Taxi,Public transport,None
10,69d398c44996bfa5e274ad6d,[2023] HKDC 784,5,XD 2420 Car,Private vehicle,None
11,69d3c8f9a7137cc8b1f7855e,[2021] HKCFI 1919,2,the defendant's flat (residence),Residential building,None
12,69d628111777bb84bcfddde5,[2024] HKDC 226,1,九龍彩盈邨盈富樓7樓713室,Residential building,None
13,69d62bf955d3e26dde17e736,[2024] HKDC 1370,1,羅湖管制站海關入境大堂,Border checkpoint,None
14,69d6f9e94fed44912e4265eb,[2022] HKDC 405,1,上海街457號梯間,Residential building,None
15,69d753a77e1b4967b315f7e4,[2026] HKCFI 847,1,貨運公司Buy & Ship的自取點（公司樓下地面）,Commercial building,None
16,69d794ba1ed324eee7ba2881,[2025] HKDC 407,1,九龍牛頭角彩霞道79號彩盈坊行人天橋上,Street,None
17,69d797c61ed324eee7ba2884,[2025] HKDC 525,1,涉案單位（單位內客廳）,Residential building,None
18,69d85f0b0bd0f7c2ddf2e2be,[2021] HKCFI 2554,1,"Hong Kong International Airport, Customs Arrival Hall (green channel)",Border checkpoint,None
19,69d87753729537f5f6f37a9b,[2024] HKDC 610,2,停泊於彩雲（一）邨彩雲商場三期地下B111、B113、及B114號舖“7-11便利店”外的一輛登記號碼為YA2167的私家車（YA2167）,Private vehicle,None

In [8]:
# --- Process each charge with GPT to infer subDistrict ---

MAX_WORKERS = 5  # Adjust based on API rate limits

results = []


def process_row(row):
    """Process a single row: infer subDistrict from address."""
    address = row['address']
    inference = infer_subdistrict(address)
    return {
        '_id': str(row['_id']),
        'charge_no': row['charge_no'],
        'neutral_citation': row['neutral_citation'],
        'address': address,
        'inferred_subDistrict': inference.subDistrict,
        'inferred_district': (
            get_district_for_subdistrict(SubDistrict(inference.subDistrict)).value
            if inference.subDistrict is not None else None
        ),
        'reason': inference.reason,
    }


if rows:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {executor.submit(process_row, row): i for i, row in enumerate(rows)}
        for future in as_completed(futures):
            idx = futures[future]
            try:
                result = future.result()
                results.append(result)
                status = '✅' if result['inferred_subDistrict'] else '❌'
                print(f"[{idx + 1}/{len(rows)}] {status} {result['neutral_citation']} "
                      f"Ch.{result['charge_no']}: {result['inferred_subDistrict'] or 'UNRESOLVED'} "
                      f"({result['address'][:60]})")
            except Exception as exc:
                print(f"[{idx + 1}/{len(rows)}] ❌ ERROR: {exc}")
                results.append({
                    '_id': str(rows[idx]['_id']),
                    'charge_no': rows[idx]['charge_no'],
                    'neutral_citation': rows[idx]['neutral_citation'],
                    'address': rows[idx]['address'],
                    'inferred_subDistrict': None,
                    'inferred_district': None,
                    'reason': f'API error: {exc}',
                })

    results_df = pd.DataFrame(results)
else:
    results_df = pd.DataFrame(columns=[
        '_id', 'charge_no', 'neutral_citation', 'address',
        'inferred_subDistrict', 'inferred_district', 'reason'
    ])

print(f"\nProcessed {len(results_df)} charges total")
print(f"  ✓ Inferred: {results_df['inferred_subDistrict'].notna().sum()}")
print(f"  ✗ Unresolved: {results_df['inferred_subDistrict'].isna().sum()}")

[1/417] ❌ [2021] HKDC 747 Ch.1: UNRESOLVED (被告人所居住的單位)
[4/417] ❌ [2021] HKCFI 574 Ch.2: UNRESOLVED (D1's residence)
[6/417] ❌ [2021] HKCFI 98 Ch.1: UNRESOLVED (Post Office)
[5/417] ❌ [2022] HKCFI 2407 Ch.2: UNRESOLVED (Building - Unknown)
[2/417] ❌ [2025] HKCFI 1364 Ch.1: UNRESOLVED (in the street near his home)
[7/417] ❌ [2025] HKCFI 4134 Ch.1: UNRESOLVED (Flat (6th floor of a building))
[3/417] ❌ [2025] HKCFI 1364 Ch.2: UNRESOLVED (inside the defendant's bedroom at his home)
[9/417] ❌ [2023] HKDC 1856 Ch.1: UNRESOLVED (Not Given)
[11/417] ❌ [2023] HKDC 784 Ch.5: UNRESOLVED (XD 2420 Car)
[8/417] ❌ [2025] HKCFI 4134 Ch.2: UNRESOLVED (Flat (the said flat rented by the defendant))
[10/417] ❌ [2023] HKCFI 925 Ch.1: UNRESOLVED (Taxi)
[12/417] ❌ [2021] HKCFI 1919 Ch.2: UNRESOLVED (the defendant's flat (residence))
[13/417] ✅ [2024] HKDC 226 Ch.1: Jordan Valley (九龍彩盈邨盈富樓7樓713室)
[14/417] ❌ [2024] HKDC 1370 Ch.1: UNRESOLVED (羅湖管制站海關入境大堂)
[18/417] ❌ [2025] HKDC 525 Ch.1: UNRESOLVED (涉案單位（單位內客廳）)
[15/417] ✅ [2022] HKDC 405 Ch.1: Yau Ma Tei (上海街457號梯間)
[16/417] ❌ [2026] HKCFI 847 Ch.1: UNRESOLVED (貨運公司Buy & Ship的自取點（公司樓下地面）)
[19/417] ✅ [2021] HKCFI 2554 Ch.1: Lantau Island (Hong Kong International Airport, Customs Arrival Hall (green)
[17/417] ✅ [2025] HKDC 407 Ch.1: Ngau Tau Kok (九龍牛頭角彩霞道79號彩盈坊行人天橋上)
[21/417] ✅ [2025] HKCFI 3027 Ch.1: Lantau Island (arrival hall of the Hong Kong International Airport)
[20/417] ✅ [2024] HKDC 610 Ch.2: Ngau Chi Wan (停泊於彩雲（一）邨彩雲商場三期地下B111、B113、及B114號舖“7-11便利店”外的一輛登記號碼為YA2167的私)
[23/417] ✅ [2025] HKCFI 1566 Ch.1: Tung Chung (Customs Arrival Hall B, Passenger Terminal Building 1, Hong )
[22/417] ❌ [2022] HKCFI 3634 Ch.1: UNRESOLVED (Defendant's residence (living room))
[24/417] ❌ [2025] HKCFI 1886 Ch.2: UNRESOLVED (Flat 714, 7th floor, Block B, Hi-tech Industrial Centre, 491)
[26/417] ✅ [2025] HKCFI 3386 Ch.1: Lantau Island (Hong Kong International Airport)
[25/417] ✅ [2025] HKCFI 3382 Ch.1: Lantau Island (bonded bus waiting lounge at the Hong Kong International Air)
[28/417] ❌ [2025] HKCFI 5254 Ch.1: UNRESOLVED (inside his private car)
[29/417] ✅ [2025] HKDC 1527 Ch.2: Wong Tai Sin (銀鳳街一個單位)
[27/417] ✅ [2025] HKCFI 4346 Ch.1: Ngau Chi Wan (Room 708, Boon Yuet House, Choi Wan (1) Estate, in Kowloon)
[30/417] ❌ [2025] HKDC 560 Ch.3: UNRESOLVED (D2's residence (inside the wardrobe in one of the bedrooms))
[31/417] ✅ [2024] HKCFI 2080 Ch.1: Tai Kok Tsui (a building at 26 Fir Street, Kowloon)
[34/417] ✅ [2024] HKDC 785 Ch.2: Mong Kok (西洋菜南街6-12號外)
[32/417] ✅ [2024] HKCFI 2885 Ch.1: Lantau Island (Hong Kong International Airport)
[36/417] ✅ [2024] HKCFI 2106 Ch.1: Tai Kok Tsui (outside No. 108D Boundary Street 8)
[33/417] ❌ [2023] HKDC 1016 Ch.1: UNRESOLVED (樂晴樓1709室)
[38/417] ❌ [2022] HKCFI 2977 Ch.1: UNRESOLVED (an unnamed road in the New Territories)
[39/417] ✅ [2025] HKCFI 2224 Ch.2: Lantau Island (Hong Kong International Airport)
[41/417] ✅ [2025] HKCFI 2377 Ch.1: Lantau Island (Customs General Cargo Examination Hall B in the Super Termin)
[35/417] ✅ [2024] HKCFI 1693 Ch.1: Lantau Island (2nd Floor, No. 32 Lam Hau Village)
[37/417] ✅ [2025] HKDC 250 Ch.1: Yuen Long (新界元朗翠桐里附近YT6885私家車)
[40/417] ✅ [2024] HKCFI 897 Ch.1: Yau Tong (a light goods vehicle bearing registration number UL512 drov)
[46/417] ✅ [2025] HKCFI 4707 Ch.1: Yau Tong (Yau Tong Estate)
[43/417] ✅ [2024] HKCFI 2104 Ch.1: Lantau Island (Customs Arrival Hall B, Passenger Terminal Building, Hong Ko)
[44/417] ✅ [2023] HKDC 677 Ch.1: Yau Ma Tei (上海街428號2樓)
[45/417] ✅ [2023] HKDC 1727 Ch.1: Kwun Tong (九龍觀塘物華街19至29號群星大廈1樓1A室)
[48/417] ✅ [2025] HKCFI 5548 Ch.1: Lantau Island (Hong Kong International Airport)
[49/417] ✅ [2025] HKCFI 6215 Ch.1: Lantau Island (Arrival Hall B of the Hong Kong International Airport)
[42/417] ❌ [2023] HKDC 1638 Ch.5: UNRESOLVED (a private car bearing registration mark of XP3700 ("V"))
[50/417] ✅ [2025] HKCFI 183 Ch.1: Lantau Island (Customs Arrival Hall B, Passenger Terminal 1, Hong Kong Inte)
[52/417] ✅ [2024] HKDC 1806 Ch.1: Kwai Chung (private car on the Tsing Kwai Highway in the New Territories)
[51/417] ✅ [2023] HKDC 206 Ch.1: Tsim Sha Tsui (彌敦道81號喜利大廈)
[54/417] ✅ [2025] HKCFI 4472 Ch.1: Lantau Island (arrival hall of the Hong Kong International Airport)
[53/417] ❌ [2025] HKCFI 2277 Ch.1: UNRESOLVED (null)
[55/417] ✅ [2024] HKDC 280 Ch.1: Mong Kok (旺角花園街)
[58/417] ✅ [2024] HKDC 836 Ch.1: To Kwa Wan (土瓜灣下鄉道8號外)
[59/417] ✅ [2023] HKCFI 1526 Ch.1: Ting Kau (Room 803, Royal View Hotel, No. 353 Castle Peak Road, Ting K)
[60/417] ✅ [2023] HKCFI 1526 Ch.2: Ting Kau (Room 803, Royal View Hotel, No. 353 Castle Peak Road, Ting K)
[57/417] ✅ [2025] HKDC 1545 Ch.1: Yuen Long (截下一輛的士並前往屯門一地點，...抵達後又指示的士載他到元朗石埗路西、錦上路牛徑村及元朗同心村；當涉案的士駛到元朗舊墟)
[62/417] ✅ [2022] HKCFI 346 Ch.1: Lantau Island (Hong Kong International Airport / handed to Customs and subs)
[61/417] ✅ [2025] HKDC 1237 Ch.1: Sham Shui Po (南昌街)
[64/417] ❌ [2024] HKDC 987 Ch.2: UNRESOLVED (被告人的睡房)
[63/417] ❌ [2024] HKDC 1064 Ch.1: UNRESOLVED (null)
[67/417] ✅ [2025] HKDC 442 Ch.1: Lantau Island (香港新界赤鱲角暢達路1號香港國際機場一號客運大樓海關入境大堂B)
[65/417] ✅ [2025] HKDC 20 Ch.1: Yau Ma Tei (九龍登打士街休憩處附近)
[66/417] ✅ [2022] HKDC 1239 Ch.1: Shek Kip Mei (九龍菩提街一帶)
[68/417] ✅ [2024] HKCFI 3665 Ch.1: Tai Wai (翠田街)
[71/417] ✅ [2024] HKCFI 3018 Ch.1: Lantau Island (Hong Kong International Airport)
[69/417] ✅ [2024] HKDC 1403 Ch.2: Wong Tai Sin (九龍獅子石道一處所（單位）)
[73/417] ✅ [2024] HKCFI 2650 Ch.4: Lok Ma Chau (a pavement near lamppost FC4101, Castle Peak Road, Mai Po, L)
[72/417] ✅ [2024] HKDC 2194 Ch.1: Ngau Tau Kok (觀塘牛頭角宏光道8號創豪坊外面)
[74/417] ✅ [2024] HKCFI 2650 Ch.5: Lok Ma Chau (4th Floor, No. 78 Mai Po Tsuen, Castle Peak Road, Mai Po, Lo)
[47/417] ❌ [2025] HKCFI 4707 Ch.2: UNRESOLVED (Defendant's residence)
[75/417] ✅ [2025] HKCFI 2138 Ch.1: Lantau Island (Customs Arrival Hall in the Hong Kong International Airport)
[77/417] ❌ [2024] HKCFI 1205 Ch.1: UNRESOLVED (the defendant's apartment / flat)
[76/417] ❌ [2023] HKDC 380 Ch.5: UNRESOLVED (不詳)
[78/417] ✅ [2024] HKDC 1273 Ch.1: Yau Ma Tei (廟街223號外)
[80/417] ✅ [2025] HKCFI 6411 Ch.1: Tung Chung (near Lamppost FB8205, Yu Tung Road, Tung Chung, Lantau Islan)
[79/417] ✅ [2025] HKDC 2162 Ch.1: Aberdeen (香港仔石排灣邨碧山樓（包括該大廈26樓1號後樓梯及2616室）)
[82/417] ❌ [2024] HKCFI 283 Ch.1: UNRESOLVED (a flat in Yeung King House, Lai King Estate, Kwai Tsing, New)
[83/417] ✅ [2024] HKCFI 945 Ch.1: Mong Kok (Mong Kok)
[85/417] ❌ [2024] HKDC 1098 Ch.1: UNRESOLVED (in a taxi on Castle Peak Road)
[84/417] ✅ [2025] HKCFI 3380 Ch.3: Yau Ma Tei (a shop / premises on Temple Street)
[56/417] ✅ [2025] HKDC 1136 Ch.1: Kwai Chung (葵涌大隴街休憩花園)
[87/417] ❌ [2024] HKDC 1437 Ch.2: UNRESOLVED (街上)
[86/417] ❌ [2025] HKCFI 424 Ch.1: UNRESOLVED (outside a shopping centre)
[88/417] ✅ [2024] HKDC 1294 Ch.1: Sha Tin (沙田松頭下路BE0252號燈柱位置)
[89/417] ✅ [2024] HKCFI 3682 Ch.1: Sha Tin (富田里, 田心村外, 沙田, 新界)
[90/417] ✅ [2024] HKCFI 3608 Ch.1: Fanling (“Chun Wah Warehouse” Lot 12 in D83, Kwan Tei, Sha Tau Kok Ro)
[91/417] ✅ [2024] HKCFI 3408 Ch.1: Tsuen Wan (Room 4218 on the 42nd Floor of Nina Hotel in Tsuen Wan West)
[93/417] ✅ [2023] HKDC 208 Ch.1: Kwai Chung (葵涌國瑞路)
[81/417] ❌ [2025] HKCFI 3686 Ch.1: UNRESOLVED (on a taxi)
[92/417] ✅ [2024] HKCFI 1100 Ch.2: Tsim Sha Tsui (Block C, Chungking Mansions, Flat C1, 11th Floor, Block C)
[94/417] ✅ [2022] HKDC 1301 Ch.1: Yau Ma Tei (香港九龍油麻地佐敦道37號外)
[95/417] ✅ [2024] HKCFI 2238 Ch.1: Hung Hom (a room at Harbour Plaza Metropolis (the Hotel))
[97/417] ❌ [2023] HKCFI 2584 Ch.2: UNRESOLVED (Room K / Unit C (subdivided unit in the flat))
[98/417] ✅ [2025] HKCFI 4897 Ch.1: Mong Kok (Sai Yee Street, Mong Kok (taxi travelling from Sheung Shui t)
[96/417] ❌ [2023] HKCFI 2584 Ch.1: UNRESOLVED (Room K / Unit C (subdivided unit in the flat))
[70/417] ✅ [2024] HKDC 1403 Ch.3: Wong Tai Sin (九龍獅子石道一處所（單位）)
[99/417] ✅ [2025] HKCFI 4372 Ch.1: Kwun Tong (a room in Kwun Tong)
[100/417] ❌ [2024] HKCFI 2417 Ch.1: UNRESOLVED (Hong Kong)
[102/417] ✅ [2025] HKCFI 5298 Ch.2: Wan Chai (Empire Hotel Hong Kong; Room 1813, Empire Hotel Hong Kong)
[101/417] ✅ [2025] HKCFI 5298 Ch.1: Wan Chai (Street outside and Room 1813 of Empire Hotel Hong Kong)
[103/417] ❌ [2023] HKCFI 2392 Ch.1: UNRESOLVED (D1’s container yard at Skye Parking, which was rented under )
[104/417] ❌ [2023] HKCFI 2392 Ch.1: UNRESOLVED (Locked container at D1’s container yard at Skye Parking (whe)
[105/417] ✅ [2023] HKDC 870 Ch.1: Kwai Chung (Kwai Yi Road)
[106/417] ✅ [2025] HKCFI 4991 Ch.1: Lantau Island (Hong Kong International Airport)
[109/417] ❌ [2025] HKCFI 5684 Ch.1: UNRESOLVED ( )
[107/417] ✅ [2021] HKDC 1604 Ch.2: Tsim Sha Tsui (金巴利道28號外的私家車SP7081)
[110/417] ✅ [2025] HKDC 538 Ch.1: Lantau Island (北大嶼山公路)
[108/417] ✅ [2025] HKCFI 5152 Ch.1: Lantau Island (Hong Kong International Airport)
[111/417] ❌ [2025] HKCFI 3265 Ch.1: UNRESOLVED (Not specified)
[115/417] ❌ [2023] HKCFI 940 Ch.1: UNRESOLVED (flat in Ma On Shan and a flat in Tsuen Wan; car park of the )
[112/417] ✅ [2025] HKCFI 3401 Ch.1: Fo Tan (Upper Ground Floor, Harry Industrial Building, Nos. 49 to 51)
[114/417] ❌ [2025] HKCFI 3401 Ch.4: UNRESOLVED (Hong Kong (various locations including Room 401 and deliveri)
[116/417] ❌ [2023] HKCFI 940 Ch.1: UNRESOLVED (flat in Ma On Shan and a flat in Tsuen Wan; car park of the )
[118/417] ✅ [2022] HKDC 788 Ch.1: Lantau Island (新界赤鱲角)
[117/417] ✅ [2025] HKDC 136 Ch.1: Sha Tin (沙田博康邨博泰樓外面)
[113/417] ✅ [2025] HKCFI 3401 Ch.2: Fo Tan (Room 401, 4th floor, Harry Industrial Building, Nos. 49 to 5)
[119/417] ✅ [2024] HKDC 1800 Ch.2: Wan Chai (alcove on G/F of 72-86 Lockhart Road, Wan Chai (sprinkler co)
[120/417] ✅ [2024] HKDC 1800 Ch.3: Wan Chai (alcove on G/F of 72-86 Lockhart Road (sprinkler control valv)
[121/417] ❌ [2025] HKCFI 2576 Ch.1: UNRESOLVED (Room A11, 19th floor (building of the consignee address))
[122/417] ❌ [2025] HKDC 954 Ch.1: UNRESOLVED (被告於控罪所指的住所)
[125/417] ❌ [2024] HKDC 1162 Ch.1: UNRESOLVED (not specified)
[123/417] ✅ [2025] HKDC 954 Ch.2: Tsuen Wan (新界荃灣海貴路車牌YY5111的私家車)
[126/417] ❌ [2023] HKDC 1313 Ch.2: UNRESOLVED (單位位於一座工業大廈（具體地址未載明）)
[127/417] ❌ [2023] HKDC 1608 Ch.1: UNRESOLVED (青朗公路（主要貫通香港元朗區、荃灣區（大欖隧道）及葵青區（青衣））)
[128/417] ✅ [2025] HKCFI 3037 Ch.1: Ha Tsuen (Sik Kong Tsuen, Ha Tsuen, Yuen Long)
[130/417] ✅ [2024] HKDC 253 Ch.2: Sau Mau Ping (九龍秀茂坪通明街53號康寧大廈xx室單位)
[129/417] ✅ [2025] HKCFI 3037 Ch.2: Lok Ma Chau (1st Floor, No. 26B of Sik Kong Tsuen)
[132/417] ✅ [2022] HKCFI 3291 Ch.1: Lantau Island (Hong Kong International Airport)
[133/417] ✅ [2025] HKDC 1648 Ch.1: Lantau Island (Hong Kong International Airport)
[131/417] ✅ [2024] HKDC 263 Ch.2: Tai Mei Tuk (汀角路EB0389號燈柱附近)
[134/417] ✅ [2025] HKDC 38 Ch.1: Ngau Tau Kok (public toilet in Chun Wah Road)
[135/417] ✅ [2025] HKCFI 2800 Ch.1: Sheung Shui (outside Flat B605, Block B, Cambridge Plaza, No. 188 San Wan)
[137/417] ✅ [2025] HKCFI 3533 Ch.1: Tin Shui Wai (near Lamppost FB0027, Tin Sam Tsuen, Tin Ha Road, Tin Shui W)
[124/417] ❌ [2024] HKCFI 2237 Ch.1: UNRESOLVED (not specified)
[139/417] ✅ [2025] HKCFI 477 Ch.1: Yau Tong (Kar Hing Building, 187 Cha Kwo Ling Road, Yau Tong (staircas)
[136/417] ✅ [2025] HKCFI 2800 Ch.2: Sheung Shui (Flat B605, Block B, Cambridge Plaza, No. 188 San Wan Road, S)
[138/417] ✅ [2025] HKCFI 3608 Ch.1: Lantau Island (arrival hall of the Hong Kong International Airport)
[141/417] ❌ [2025] HKCFI 5491 Ch.1: UNRESOLVED (Shenzhen (People's Republic of China) and various locations )
[140/417] ✅ [2025] HKCFI 477 Ch.2: Yau Tong (Unit on the 2/F (Flat D), Kar Hing Building, 187 Cha Kwo Lin)
[142/417] ✅ [2022] HKCFI 2990 Ch.1: Mong Kok (砵蘭街一間酒店)
[143/417] ✅ [2025] HKDC 258 Ch.1: Luk Keng (Warehouse D, Lot 22, DD 37, No.5 Wo Keng Shan Road, Wo Keng )
[145/417] ✅ [2024] HKCFI 673 Ch.1: Sham Shui Po (near the junction of Un Chau Street and Kweilin Street)
[147/417] ✅ [2023] HKCFI 2648 Ch.1: Tsuen Wan (outside Lee Yuen Dim Sum Restaurant, Tsuen Wan Centre at Tsu)
[144/417] ✅ [2025] HKDC 258 Ch.2: Luk Keng (Warehouse D, Lot 22, DD 37, No.5 Wo Keng Shan Road, Wo Keng )
[146/417] ✅ [2024] HKDC 1653 Ch.1: Yau Ma Tei (九龍油麻地登打士街與東安街交界（在登記號碼為YL7921的私家車上）)
[148/417] ✅ [2023] HKCFI 2648 Ch.2: Tai Po (Ground Floor, No. 65, Wai Tau Tsuen, Tai Wo Service Road Wes)
[151/417] ❌ [2024] HKCFI 450 Ch.1: UNRESOLVED (a factory building)
[152/417] ❌ [2024] HKCFI 450 Ch.2: UNRESOLVED (a room in a factory building)
[150/417] ✅ [2021] HKCFI 914 Ch.1: Lantau Island (Customs Arrival Hall A, Terminal 1, Hong Kong International )
[154/417] ✅ [2025] HKCFI 5930 Ch.1: Tsing Yi (outside Tsing Yi Post Office in Tsing Yi)
[156/417] ✅ [2025] HKDC 658 Ch.1: Fanling (一鳴路及百和路交界及其附近（包括駛往中石化油站方向、百和路與偉明街交界、百和路與一鳴路交界等路段）)
[153/417] ✅ [2025] HKCFI 5310 Ch.1: Lantau Island (Hong Kong International Airport)
[155/417] ✅ [2025] HKDC 1343 Ch.1: Sham Shui Po (the junction of Cheung Sha Wan Road and Nam Cheong Street)
[157/417] ❌ [2025] HKCFI 2096 Ch.2: UNRESOLVED (D2's home)
[149/417] ✅ [2023] HKDC 1414 Ch.1: Tsing Yi (青衣路一商場外)
[160/417] ✅ [2021] HKCFI 3324 Ch.3: Yuen Long (41A, Wang Chau Fuk Hing Tsuen, Fuk Hi Street, Yuen Long)
[158/417] ✅ [2023] HKCFI 1151 Ch.1: Lantau Island (Hong Kong International Airport)
[159/417] ✅ [2024] HKDC 272 Ch.2: Lok Ma Chau (深圳灣管制站入境貨車檢查亭，海關人員在海關入境貨物檢查大樓G04A室)
[161/417] ✅ [2021] HKCFI 3324 Ch.4: Yuen Long (41A, Wang Chau Fuk Hing Tsuen, Fuk Hi Street, Yuen Long)
[164/417] ❌ [2024] HKCFI 867 Ch.1: UNRESOLVED (Defendant's residence)
[163/417] ❌ [2022] HKCFI 3223 Ch.2: UNRESOLVED (Customs)
[162/417] ✅ [2021] HKCFI 3324 Ch.5: Yuen Long (41A, Wang Chau Fuk Hing Tsuen, Fuk Hi Street, Yuen Long)
[166/417] ✅ [2023] HKDC 660 Ch.3: Ting Kau (香港新界汀九青山公路—汀九段)
[167/417] ❌ [2023] HKCFI 1155 Ch.2: UNRESOLVED (not given)
[168/417] ✅ [2025] HKDC 387 Ch.1: Tung Chung (東涌逸東邨)
[170/417] ❌ [2023] HKDC 1222 Ch.1: UNRESOLVED (香港)
[165/417] ✅ [2023] HKDC 660 Ch.2: Ting Kau (香港新界汀九青山公路—汀九段)
[171/417] ✅ [2025] HKDC 35 Ch.1: Yau Ma Tei (砵蘭街)
[173/417] ✅ [2025] HKCFI 5540 Ch.1: Tuen Mun (unit on the 7th floor of Mai Kei Industrial Building, Tuen M)
[174/417] ❌ [2025] HKCFI 5936 Ch.1: UNRESOLVED (null)
[169/417] ❌ [2023] HKDC 1078 Ch.1: UNRESOLVED (not given)
[172/417] ✅ [2022] HKDC 1021 Ch.1: Chai Wan (柴灣道東行第三線)
[177/417] ❌ [2021] HKCFI 3164 Ch.1: UNRESOLVED (an address in Jordan Road)
[176/417] ✅ [2024] HKCFI 796 Ch.1: Lantau Island (Hong Kong International Airport)
[179/417] ❌ [2023] HKCFI 912 Ch.2: UNRESOLVED (not given)
[180/417] ✅ [2024] HKCFI 1583 Ch.1: Lantau Island (Hong Kong International Airport)
[175/417] ✅ [2024] HKDC 1194 Ch.3: Kwai Chung (悅品酒店1914室 / 悅品酒店停車場，葵涌青山公路)
[182/417] ✅ [2023] HKDC 1003 Ch.1: Yau Ma Tei (登打士街8號外)
[181/417] ✅ [2023] HKCFI 3336 Ch.1: Kai Tak (a flat in K City, Kai Tak, Kowloon)
[184/417] ✅ [2022] HKDC 112 Ch.2: Tin Shui Wai (near Lamppost No FA9853, outside Tin Yiu Plaza, No 2 Tin Wu )
[183/417] ✅ [2024] HKDC 1842 Ch.1: Ngau Chi Wan (outside Yok Yu House in Choi Wan Estate)
[178/417] ❌ [2022] HKDC 723 Ch.1: UNRESOLVED (被告人坐於涉案的私家車司機位，停在案發現場引擎正開動，車匙插在開關內。)
[187/417] ✅ [2024] HKDC 1185 Ch.1: Tsim Sha Tsui (在一輛停泊在九龍尖沙咀山林道和彌敦道交界的車內)
[185/417] ❌ [2024] HKDC 519 Ch.1: UNRESOLVED (被告人住所（背囊內被發現毒品）；荃灣眾安街與兆和街路口（接收）；葵興港鐵站（接收）；九龍黃大仙竹園道10號竹園體育館外（)
[186/417] ✅ [2024] HKDC 527 Ch.1: Ho Man Tin (窩打老道(北行))
[188/417] ✅ [2023] HKDC 777 Ch.1: Tin Shui Wai (景湖居3座13樓A室睡房)
[189/417] ✅ [2023] HKDC 1162 Ch.1: Hung Hom (紅磡啟明街與玉成街交界，旺德大廈)
[192/417] ✅ [2021] HKCFI 2036 Ch.1: Lantau Island (Customs Arrival Hall A, Passenger Terminal 1, Hong Kong Inte)
[191/417] ✅ [2024] HKDC 434 Ch.2: Pat Heung (near Lamppost No.VD4685 at Kam Tin Road, Pat Heung, Yuen Lon)
[193/417] ✅ [2022] HKCFI 3528 Ch.1: Lantau Island (Transit Lounge E2, Level 5, Passenger Terminal Building 1, H)
[194/417] ✅ [2022] HKCFI 3528 Ch.2: Lantau Island (Transit Lounge E2, Level 5, Passenger Terminal Building 1, H)
[190/417] ✅ [2024] HKDC 2161 Ch.1: Lantau Island (Hong Kong International Airport)
[195/417] ✅ [2024] HKDC 930 Ch.1: Lam Tei (新界藍地青山公路 — 藍地段順風圍389號Al號屋地下外面無名村路其中一個泊車位（涉案地點）)
[197/417] ❌ [2025] HKDC 615 Ch.2: UNRESOLVED (羅湖管制站海關離境大堂)
[199/417] ✅ [2022] HKDC 689 Ch.1: Kai Tak (啟德德朗邨德瑤樓3020室（及其地下升降機大堂）)
[198/417] ❌ [2023] HKDC 959 Ch.1: UNRESOLVED (乾豐大廈3樓D室)
[201/417] ✅ [2023] HKCFI 1268 Ch.1: Tin Shui Wai (a room at the Harbour Plaza Resort City)
[196/417] ❌ [2025] HKDC 615 Ch.1: UNRESOLVED (香港羅湖管制站海關離境大堂)
[200/417] ✅ [2024] HKCFI 2828 Ch.1: Lantau Island (Hong Kong International Airport)
[202/417] ✅ [2023] HKCFI 1268 Ch.3: Tin Shui Wai (a room at the Harbour Plaza Resort City)
[204/417] ❌ [2025] HKCFI 1294 Ch.1: UNRESOLVED (Defendant's home)
[205/417] ❌ [2024] HKCFI 1707 Ch.3: UNRESOLVED (Hong Kong)
[203/417] ✅ [2025] HKDC 1100 Ch.1: Lantau Island (香港國際機場入境大堂，14號行李輸送帶)
[207/417] ✅ [2025] HKCFI 1517 Ch.2: Mong Kok (Room 1818, iClub Hotel, No. 2 Anchor Street, Mong Kok, Kowlo)
[206/417] ✅ [2025] HKCFI 1517 Ch.1: Yau Ma Tei (Operation Room 9B, Kwong Wah Hospital, No. 25 Waterloo Road,)
[209/417] ✅ [2023] HKDC 167 Ch.1: Sham Shui Po (junction of Tai Nan Street and Wong Chuk Street ... hit the )
[211/417] ❌ [2025] HKCFI 4253 Ch.2: UNRESOLVED (Hong Kong)
[212/417] ❌ [2025] HKCFI 4253 Ch.3: UNRESOLVED (Hong Kong)
[210/417] ❌ [2025] HKCFI 4253 Ch.1: UNRESOLVED (Hong Kong)
[213/417] ✅ [2024] HKCFI 2757 Ch.1: Tsim Sha Tsui (Room 507, Chungking Mansion)
[208/417] ✅ [2025] HKDC 299 Ch.1: Tsim Sha Tsui (海防大廈 9樓 904號房（"Pretty Inn"）)
[216/417] ✅ [2025] HKCA 234 Ch.1: Lantau Island (Hong Kong International Airport, Lantau Island, New Territor)
[214/417] ❌ [2024] HKDC 1007 Ch.1: UNRESOLVED (該酒店1719號房間 (17樓))
[215/417] ✅ [2023] HKDC 502 Ch.1: Tsing Yi (青衣長宏邨)
[220/417] ✅ [2022] HKCFI 3344 Ch.2: Yuen Long (新界元朗青山公路（屏山段）御豪山莊11座3樓A室)
[221/417] ✅ [2024] HKCFI 1503 Ch.1: Sham Shui Po (on the podium of a housing estate in Sham Shui Po)
[219/417] ✅ [2022] HKCFI 3344 Ch.1: Yuen Long (新界元朗青山公路（屏山段）御豪山莊11座外)
[217/417] ✅ [2022] HKDC 1129 Ch.1: Wong Tai Sin (Carpark of Tsz Ching Estate, Wong Tai Sin)
[218/417] ✅ [2021] HKCFI 2324 Ch.1: Lantau Island (Customs Arrival Hall, Hong Kong International Airport)
[222/417] ✅ [2024] HKCFI 1503 Ch.2: Sham Shui Po (the defendant’s residence at the same housing estate in Sham)
[225/417] ✅ [2025] HKCFI 1155 Ch.1: Tuen Mun (Fuk Hang Tsuen Road, Tuen Mun, New Territories, Hong Kong (t)
[223/417] ✅ [2023] HKCFI 943 Ch.2: Mong Kok (No. 35 Dundas Street, Mong Kok)
[224/417] ✅ [2025] HKCFI 488 Ch.1: Lantau Island (Hong Kong International Airport)
[228/417] ✅ [2023] HKCFI 2670 Ch.1: Pat Heung (Outside Wai Kei BBQ, 677 Tai Kei Leng Road, New Territories )
[227/417] ❌ [2022] HKCFI 1886 Ch.1: UNRESOLVED (Room 1322)
[226/417] ✅ [2023] HKCFI 1132 Ch.2: Kwai Chung (Kwai Chung Container Terminal 1 (collection point for three )
[229/417] ✅ [2021] HKCFI 2117 Ch.1: Lantau Island (Hong Kong International Airport)
[231/417] ❌ [2024] HKCFI 2457 Ch.2: UNRESOLVED (the defendant’s residence)
[234/417] ✅ [2024] HKCFI 3410 Ch.1: Tin Shui Wai (between Tin Tan Street and Tin Shui Road, Tin Shui Wai)
  WARNING: GPT returned invalid subDistrict 'Jordan' for address '九龍油地佐敦道與吳松街交界附近'
[232/417] ❌ [2024] HKDC 7 Ch.1: UNRESOLVED (九龍油地佐敦道與吳松街交界附近)
[230/417] ✅ [2024] HKCFI 2457 Ch.1: Shau Kei Wan (outside a building at Yiu Tung Street)
[233/417] ✅ [2022] HKDC 1338 Ch.1: Yau Ma Tei (砵蘭街)
[235/417] ✅ [2024] HKCFI 3410 Ch.2: Pok Fu Lam (a unit in Wah Fu Estate)
[237/417] ✅ [2022] HKDC 562 Ch.1: Fo Tan (青沙公路，近燈柱 CF8059 / CF8063)
[236/417] ✅ [2022] HKDC 39 Ch.1: Tsuen Wan (石圍角邨石蘭樓的停車場內)
[238/417] ✅ [2022] HKDC 599 Ch.1: Yau Ma Tei (Man Ying Street, Jordan, Kowloon)
[240/417] ✅ [2021] HKCFI 1158 Ch.2: So Kwun Wat (Flat A, 22nd Floor, Block 3, Hong Kong Gold Coast, Phase 1 ()
[239/417] ✅ [2021] HKCFI 1158 Ch.1: Tuen Mun (a flat in Tower 7 of Avignon, in Tuen Mun (cocaine found in )
[241/417] ✅ [2023] HKDC 1615 Ch.1: Tsim Sha Tsui (由金馬倫道沿金馬倫里向加拿芬道方向急步行)
[242/417] ✅ [2022] HKDC 438 Ch.1: Tsim Sha Tsui (漢口道)
[244/417] ✅ [2024] HKDC 1491 Ch.1: Tin Shui Wai (天瑞商場一間店鋪外)
[246/417] ✅ [2023] HKDC 1268 Ch.1: Mong Kok (the junction of Nelson Street and Portland Street)
[243/417] ✅ [2023] HKCFI 554 Ch.1: Lantau Island (香港大嶼山赤鱲角香港國際機場)

In [9]:
# --- Write inferred subDistricts back to MongoDB ---

# Only write rows where we successfully inferred a subDistrict
inferred_rows = results_df[results_df['inferred_subDistrict'].notna()].to_dict('records')

update_operations = []
for row in inferred_rows:
    subdistrict_value = row['inferred_subDistrict']
    district_value = row['inferred_district']
    source_text = (
        f"Inferred from address '{row['address']}' using GPT-5.4: {row['reason']}"
    )

    update_operations.append(
        UpdateOne(
            {
                '_id': ObjectId(row['_id']),
                'judgement.charges.charge_no': row['charge_no'],
            },
            {
                '$set': {
                    'judgement.charges.$[charge].place_of_offence.subDistrict': subdistrict_value,
                    'judgement.charges.$[charge].place_of_offence.district': district_value,
                }
            },
            array_filters=[
                {'charge.charge_no': row['charge_no']},
            ],
        )
    )

update_result = None
if update_operations:
    update_result = verified_features.bulk_write(update_operations, ordered=False)
    print(f"Written {update_result.modified_count} charge(s) with inferred subDistricts")
else:
    print("No subDistricts to write back")

Written 291 charge(s) with inferred subDistricts

In [14]:
# --- Export unresolved cases to Excel ---
unresolved = results_df[results_df['inferred_subDistrict'].isna()].copy()

unresolved_columns = [
    'neutral_citation',
    'charge_no',
    'address',
    'reason',
]


def _sanitize_for_excel(value):
    """Remove Excel-illegal control characters from string values."""
    if isinstance(value, str):
        return re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f]', '', value)
    return value


if not unresolved.empty:
    unresolved_out = unresolved[unresolved_columns].sort_values(
        ['neutral_citation', 'charge_no']
    ).reset_index(drop=True)
    # Sanitize all string columns to remove Excel-illegal characters
    unresolved_out = unresolved_out.map(_sanitize_for_excel)
    unresolved_out.to_excel('unresolved_subdistricts.xlsx', index=False)
    print(f"Exported {len(unresolved_out)} unresolved cases to 'unresolved_subdistricts.xlsx'")
    display(unresolved_out)
else:
    print("All cases resolved! No unresolved subDistricts.")
    # Create empty file for consistency
    pd.DataFrame(columns=unresolved_columns).to_excel(
        'unresolved_subdistricts.xlsx', index=False
    )

# Also export resolved cases for reference
resolved = results_df[results_df['inferred_subDistrict'].notna()].copy()

if not resolved.empty:
    resolved_out = resolved.sort_values(
        ['neutral_citation', 'charge_no']
    ).reset_index(drop=True).map(_sanitize_for_excel)
    resolved_out.to_excel('resolved_subdistricts.xlsx', index=False)
    print(f"Exported {len(resolved_out)} resolved cases to 'resolved_subdistricts.xlsx'")


# Also export full results for reference
results_df_sanitized = results_df.map(_sanitize_for_excel)
results_df_sanitized.to_excel('subdistrict_inference_results.xlsx', index=False)

print("Exported full results to 'subdistrict_inference_results.xlsx'")

Exported 126 unresolved cases to 'unresolved_subdistricts.xlsx'

,neutral_citation,charge_no,address,reason
0,[2021] HKCFI 1411,2,輕型貨車停於九龍塘達之路；及後於沙田一間酒店房間進行搜查並發現毒品,"The address mentions two different locations: 達之路 in 九龍塘 (which points to Kowloon Tong) and later a hotel room in 沙田 (which points to Sha Tin). Because the event spans multiple places and does not specify which single location should be assigned, a unique sub-district cannot be determined."
1,[2021] HKCFI 1919,2,the defendant's flat (residence),"The address 'the defendant's flat (residence)' provides no geographic clue or Hong Kong location information, so it cannot be matched to any listed sub-district."
2,[2021] HKCFI 2021,1,Post office,"""Post office"" is too vague and does not indicate any specific location in Hong Kong, so it cannot be mapped to a single known sub-district."
3,[2021] HKCFI 2396,2,Not given,"No address was provided ('Not given'), so the sub-district cannot be determined."
4,[2021] HKCFI 2596,3,garage,"The address 'garage' is too vague and provides no location clue in Hong Kong, so it cannot be mapped to any listed sub-district."
...,...,...,...,...
121,[2025] HKDC 615,1,香港羅湖管制站海關離境大堂,「羅湖管制站海關離境大堂」指的是羅湖口岸／Lo Wu Control Point。『羅湖』不在提供的有效子地區清單中；雖然其位置接近 Sheung Shui 一帶，但口岸本身無法明確對應到清單中的某一子地區，因此不應勉強推斷。
122,[2025] HKDC 615,2,羅湖管制站海關離境大堂,「羅湖管制站海關離境大堂」指羅湖管制站（Lo Wu Control Point）。雖然羅湖位於新界北部、鄰近上水／文錦渡一帶，但「羅湖」本身不在提供的有效子分區清單內，且不能明確對應到清單中的某一個子分區，因此不應勉強猜測。
123,[2025] HKDC 754,1,被告人的家中的睡房電腦枱上的塑膠抽屜,"The provided text only says 'the plastic drawer on the bedroom computer desk in the defendant’s home' and gives no Hong Kong location clue such as district, estate, street, building, or landmark, so the sub-district cannot be determined."
124,[2025] HKDC 954,1,被告於控罪所指的住所,"The address provided,「被告於控罪所指的住所」, is not an actual Hong Kong location but a generic legal phrase meaning 'the defendant's residence referred to in the charge'. It contains no identifiable geographic clue to map to any listed sub-district."
125,[2026] HKCFI 847,1,貨運公司Buy & Ship的自取點（公司樓下地面）,地址只有「貨運公司Buy & Ship的自取點（公司樓下地面）」，未提供街道、屋苑、大廈、地區或分區名稱，無法對應到任何明確的香港分區。

Exported 291 resolved cases to 'resolved_subdistricts.xlsx'
Exported full results to 'subdistrict_inference_results.xlsx'

In [16]:
# --- Export cases without address and subDistrict ---

# These are charges where both address and subDistrict are null/empty:
# the place of offence was simply not mentioned in the judgment.
# They differ from 'unresolved' cases (which have an address but GPT couldn't infer subDistrict).

pipeline_no_address = []
if active_only:
    pipeline_no_address.append({'$match': {'exclude': {'$ne': True}}})

pipeline_no_address.extend([
    {'$unwind': '$judgement.charges'},
    # Filter to charges where BOTH address and subDistrict are null/empty
    {'$match': {
        'judgement.charges.place_of_offence': {'$ne': None},
        '$expr': {
            '$and': [
                # address is null or empty
                {'$or': [
                    {'$eq': ['$judgement.charges.place_of_offence.address', None]},
                    {'$eq': ['$judgement.charges.place_of_offence.address', '']},
                ]},
                # subDistrict is null or empty
                {'$or': [
                    {'$eq': ['$judgement.charges.place_of_offence.subDistrict', None]},
                    {'$eq': ['$judgement.charges.place_of_offence.subDistrict', '']},
                ]},
            ]
        },
    }},
    {
        '$project': {
            '_id': 1,
            'neutral_citation': '$judgement.neutral_citation',
            'charge_no': '$judgement.charges.charge_no',
            'address': '$judgement.charges.place_of_offence.address',
            'nature': '$judgement.charges.place_of_offence.nature',
            'subDistrict': '$judgement.charges.place_of_offence.subDistrict',
        }
    },
])

rows_no_address = list(verified_features.aggregate(pipeline_no_address, allowDiskUse=True))
print(f"Found {len(rows_no_address)} charges with neither address nor subDistrict")

if rows_no_address:
    df_no_address = pd.DataFrame(rows_no_address)
    df_no_address['_id'] = df_no_address['_id'].apply(str)

    # Subtract charges already in the processed results
    processed_ids = set(zip(results_df['_id'], results_df['charge_no']))
    df_no_address = df_no_address[
        ~df_no_address.apply(lambda r: (r['_id'], r['charge_no']) in processed_ids, axis=1)
    ]

    columns = ['neutral_citation', 'charge_no', 'nature']

    if not df_no_address.empty:
        out = df_no_address[columns].sort_values(
            ['neutral_citation', 'charge_no']
        ).reset_index(drop=True)
        out = out.map(_sanitize_for_excel)
        out.to_excel('cases_without_address_subdistrict.xlsx', index=False)
        n = len(out)
        print(f"Exported {n} cases without address/subDistrict to cases_without_address_subdistrict.xlsx")
        display(out)
    else:
        print("All address-less cases were already captured in the processed results.")
else:
    print("No cases without address found.")

Found 134 charges with neither address nor subDistrict
Exported 134 cases without address/subDistrict to cases_without_address_subdistrict.xlsx

      neutral_citation  charge_no                nature
0    [2021] HKCFI 1393          1       Private vehicle
1    [2021] HKCFI 1963          1     Border checkpoint
2    [2021] HKCFI 2074          1       Private vehicle
3    [2021] HKCFI 2091          1  Residential building
4    [2021] HKCFI 2596          2       Private vehicle
..                 ...        ...                   ...
129     [2025] HKDC 57          2       Private vehicle
130    [2025] HKDC 827          1  Residential building
131    [2025] HKDC 880          1  Residential building
132    [2025] HKDC 964          1      Public transport
133   [2026] HKCFI 747          1      Public transport

[134 rows x 3 columns]

In [15]:
# --- Summary ---

total = len(results_df)
resolved = results_df['inferred_subDistrict'].notna().sum()
unresolved_count = results_df['inferred_subDistrict'].isna().sum()

print("=" * 60)
print("SUMMARY: Infer Missing subDistricts")
print("=" * 60)
print(f"Total charges processed:  {total}")
print(f"Successfully inferred:    {resolved} ({resolved / total * 100:.1f}%)" if total else "N/A")
print(f"Still unresolved:         {unresolved_count} ({unresolved_count / total * 100:.1f}%)" if total else "N/A")
print()
if update_result:
    print(f"DB writes:               {update_result.modified_count} modified")
print()
if unresolved_count > 0:
    print(f"See 'unresolved_subdistricts.xlsx' for cases needing manual review.")
print(f"See 'subdistrict_inference_results.xlsx' for full results.")
print("=" * 60)

============================================================
SUMMARY: Infer Missing subDistricts
============================================================
Total charges processed:  417
Successfully inferred:    291 (69.8%)
Still unresolved:         126 (30.2%)

DB writes:               291 modified

See 'unresolved_subdistricts.xlsx' for cases needing manual review.
See 'subdistrict_inference_results.xlsx' for full results.
============================================================